export type PartCatalogNodeSeed = {
  name: string;
  slug: string;
  description?: string;
  categorySlug?: string;
  children?: PartCatalogNodeSeed[];
};

const SOURCE_NAME = "SUPERCAR DASH catalog shell inspired by common automotive part-group taxonomy";
const SOURCE_URL = "https://www.rockauto.com/en/parts/";

export const PART_CATALOG_TAXONOMY_SOURCE = {
  name: SOURCE_NAME,
  url: SOURCE_URL,
};

export const PART_CATALOG_TAXONOMY_SEEDS: PartCatalogNodeSeed[] = [
  {
    name: "Accessories & Appearance",
    slug: "accessories-appearance",
    description: "Exterior appearance, care, protection, covers, decals, and universal accessories.",
    children: [
      { name: "Car Cover", slug: "car-cover" },
      { name: "Floor Mat", slug: "floor-mat", categorySlug: "interior-safety" },
      { name: "License Plate Bracket", slug: "license-plate-bracket" },
      { name: "Paint Protection Film", slug: "paint-protection-film", categorySlug: "aero-body" },
      { name: "Detailing Kit", slug: "detailing-kit" },
      { name: "Battery Tender", slug: "battery-tender" },
      { name: "Tow Hook", slug: "tow-hook", categorySlug: "aero-body" },
      { name: "Splash Guard", slug: "splash-guard", categorySlug: "aero-body" },
    ],
  },
  {
    name: "Air & Fuel Delivery",
    slug: "air-fuel-delivery",
    description: "Air intake, throttle, fuel delivery, fuel storage, and induction support parts.",
    children: [
      { name: "Air Filter", slug: "air-filter", categorySlug: "intake" },
      { name: "Air Intake System", slug: "air-intake-system", categorySlug: "intake" },
      { name: "Cold Air Intake", slug: "cold-air-intake", categorySlug: "intake" },
      { name: "Intake Manifold", slug: "intake-manifold", categorySlug: "intake" },
      { name: "Mass Air Flow Sensor", slug: "mass-air-flow-sensor", categorySlug: "ecu-tuning" },
      { name: "Throttle Body", slug: "throttle-body", categorySlug: "intake" },
      { name: "Throttle Body Spacer", slug: "throttle-body-spacer", categorySlug: "intake" },
      { name: "Fuel Filter", slug: "fuel-filter", categorySlug: "fueling" },
      { name: "Fuel Injector", slug: "fuel-injector", categorySlug: "fueling" },
      { name: "Fuel Line", slug: "fuel-line", categorySlug: "fueling" },
      { name: "Fuel Pressure Regulator", slug: "fuel-pressure-regulator", categorySlug: "fueling" },
      { name: "Fuel Pump", slug: "fuel-pump", categorySlug: "fueling" },
      { name: "Fuel Rail", slug: "fuel-rail", categorySlug: "fueling" },
      { name: "Fuel Tank", slug: "fuel-tank", categorySlug: "fueling" },
      { name: "Flex Fuel Kit", slug: "flex-fuel-kit", categorySlug: "fueling" },
    ],
  },
  {
    name: "Belt Drive",
    slug: "belt-drive",
    description: "Accessory belts, pulleys, tensioners, and belt-drive service parts.",
    children: [
      { name: "Accessory Drive Belt", slug: "accessory-drive-belt" },
      { name: "Belt Tensioner", slug: "belt-tensioner" },
      { name: "Idler Pulley", slug: "idler-pulley" },
      { name: "Supercharger Belt", slug: "supercharger-belt", categorySlug: "forced-induction" },
      { name: "Timing Belt", slug: "timing-belt" },
      { name: "Timing Belt Kit", slug: "timing-belt-kit" },
      { name: "Tensioner Pulley", slug: "tensioner-pulley" },
    ],
  },
  {
    name: "Body & Lamp Assembly",
    slug: "body-lamp-assembly",
    description: "Body panels, lighting, trim, glass, mirrors, and exterior mounting parts.",
    children: [
      { name: "Aero Splitter", slug: "aero-splitter", categorySlug: "aero-body" },
      { name: "Bumper Cover", slug: "bumper-cover", categorySlug: "aero-body" },
      { name: "Carbon Fiber Hood", slug: "carbon-fiber-hood", categorySlug: "aero-body" },
      { name: "Diffuser", slug: "diffuser", categorySlug: "aero-body" },
      { name: "Door Shell", slug: "door-shell" },
      { name: "Fender", slug: "fender", categorySlug: "aero-body" },
      { name: "Grille", slug: "grille", categorySlug: "aero-body" },
      { name: "Headlamp Assembly", slug: "headlamp-assembly" },
      { name: "Hood", slug: "hood", categorySlug: "aero-body" },
      { name: "Mirror Assembly", slug: "mirror-assembly" },
      { name: "Quarter Panel", slug: "quarter-panel" },
      { name: "Rocker Panel", slug: "rocker-panel", categorySlug: "aero-body" },
      { name: "Spoiler", slug: "spoiler", categorySlug: "aero-body" },
      { name: "Tail Lamp Assembly", slug: "tail-lamp-assembly" },
      { name: "Undertray", slug: "undertray", categorySlug: "aero-body" },
      { name: "Windshield", slug: "windshield" },
    ],
  },
  {
    name: "Brake & Wheel Hub",
    slug: "brake-wheel-hub",
    description: "Brake friction, hydraulic, hub, bearing, and wheel-end service parts.",
    categorySlug: "brakes",
    children: [
      { name: "ABS Sensor", slug: "abs-sensor" },
      { name: "Big Brake Kit", slug: "big-brake-kit", categorySlug: "brakes" },
      { name: "Brake Booster", slug: "brake-booster", categorySlug: "brakes" },
      { name: "Brake Caliper", slug: "brake-caliper", categorySlug: "brakes" },
      { name: "Brake Cooling Duct", slug: "brake-cooling-duct", categorySlug: "brakes" },
      { name: "Brake Fluid", slug: "brake-fluid", categorySlug: "brakes" },
      { name: "Brake Hose", slug: "brake-hose", categorySlug: "brakes" },
      { name: "Brake Line", slug: "brake-line", categorySlug: "brakes" },
      { name: "Brake Pad", slug: "brake-pad", categorySlug: "brakes" },
      { name: "Brake Rotor", slug: "brake-rotor", categorySlug: "brakes" },
      { name: "Brake Shoe", slug: "brake-shoe", categorySlug: "brakes" },
      { name: "Master Cylinder", slug: "master-cylinder", categorySlug: "brakes" },
      { name: "Parking Brake Cable", slug: "parking-brake-cable", categorySlug: "brakes" },
      { name: "Wheel Bearing", slug: "wheel-bearing" },
      { name: "Wheel Hub", slug: "wheel-hub" },
      { name: "Wheel Stud", slug: "wheel-stud", categorySlug: "wheels-tires" },
    ],
  },
  {
    name: "Cooling System",
    slug: "cooling-system",
    description: "Radiators, fans, coolant plumbing, thermostat, oil cooling, and heat management.",
    categorySlug: "cooling",
    children: [
      { name: "Coolant Hose", slug: "coolant-hose", categorySlug: "cooling" },
      { name: "Expansion Tank", slug: "expansion-tank", categorySlug: "cooling" },
      { name: "Fan Clutch", slug: "fan-clutch", categorySlug: "cooling" },
      { name: "Heat Exchanger", slug: "heat-exchanger", categorySlug: "cooling" },
      { name: "Intercooler", slug: "intercooler", categorySlug: "forced-induction" },
      { name: "Oil Cooler", slug: "oil-cooler", categorySlug: "cooling" },
      { name: "Radiator", slug: "radiator", categorySlug: "cooling" },
      { name: "Radiator Cap", slug: "radiator-cap", categorySlug: "cooling" },
      { name: "Radiator Fan", slug: "radiator-fan", categorySlug: "cooling" },
      { name: "Radiator Shroud", slug: "radiator-shroud", categorySlug: "cooling" },
      { name: "Thermostat", slug: "thermostat", categorySlug: "cooling" },
      { name: "Water Pump", slug: "water-pump", categorySlug: "cooling" },
    ],
  },
  {
    name: "Drivetrain & Axle",
    slug: "drivetrain-axle",
    description: "Axles, CV joints, driveshafts, differentials, mounts, clutches, and drivetrain hardware.",
    categorySlug: "drivetrain",
    children: [
      { name: "Axle Shaft", slug: "axle-shaft", categorySlug: "drivetrain" },
      { name: "CV Axle", slug: "cv-axle", categorySlug: "drivetrain" },
      { name: "CV Joint", slug: "cv-joint", categorySlug: "drivetrain" },
      { name: "Differential", slug: "differential", categorySlug: "drivetrain" },
      { name: "Differential Bushing", slug: "differential-bushing", categorySlug: "drivetrain" },
      { name: "Driveshaft", slug: "driveshaft", categorySlug: "drivetrain" },
      { name: "Engine Mount", slug: "engine-mount", categorySlug: "drivetrain" },
      { name: "Flywheel", slug: "flywheel", categorySlug: "drivetrain" },
      { name: "Limited Slip Differential", slug: "limited-slip-differential", categorySlug: "drivetrain" },
      { name: "Transmission Mount", slug: "transmission-mount", categorySlug: "drivetrain" },
    ],
  },
  {
    name: "Electrical",
    slug: "electrical",
    description: "Battery, charging, lighting electronics, sensors, relays, wiring, and vehicle control modules.",
    children: [
      { name: "Alternator", slug: "alternator" },
      { name: "Battery", slug: "battery" },
      { name: "Battery Cable", slug: "battery-cable" },
      { name: "Body Control Module", slug: "body-control-module" },
      { name: "Fuse", slug: "fuse" },
      { name: "Fuse Box", slug: "fuse-box" },
      { name: "Ground Strap", slug: "ground-strap" },
      { name: "Lighting Control Module", slug: "lighting-control-module" },
      { name: "Relay", slug: "relay" },
      { name: "Sensor", slug: "sensor" },
      { name: "Starter Motor", slug: "starter-motor" },
      { name: "Wiring Harness", slug: "wiring-harness" },
    ],
  },
  {
    name: "Engine",
    slug: "engine",
    description: "Internal engine, lubrication, valvetrain, gaskets, timing, and service components.",
    children: [
      { name: "Camshaft", slug: "camshaft" },
      { name: "Connecting Rod", slug: "connecting-rod" },
      { name: "Crankshaft", slug: "crankshaft" },
      { name: "Cylinder Head", slug: "cylinder-head" },
      { name: "Engine Gasket Set", slug: "engine-gasket-set" },
      { name: "Head Gasket", slug: "head-gasket" },
      { name: "Oil Filter", slug: "oil-filter" },
      { name: "Oil Pan", slug: "oil-pan" },
      { name: "Oil Pump", slug: "oil-pump" },
      { name: "Piston", slug: "piston" },
      { name: "Timing Chain", slug: "timing-chain" },
      { name: "Timing Cover", slug: "timing-cover" },
      { name: "Timing Gear", slug: "timing-gear", categorySlug: "drivetrain" },
      { name: "Valve Cover", slug: "valve-cover" },
      { name: "Valve Spring", slug: "valve-spring" },
    ],
  },
  {
    name: "Exhaust & Emission",
    slug: "exhaust-emission",
    description: "Headers, manifolds, cats, resonators, mufflers, valved systems, and emissions sensors.",
    categorySlug: "exhaust",
    children: [
      { name: "Catalytic Converter", slug: "catalytic-converter", categorySlug: "exhaust" },
      { name: "Cat-Back Exhaust", slug: "cat-back-exhaust", categorySlug: "exhaust" },
      { name: "Downpipe", slug: "downpipe", categorySlug: "exhaust" },
      { name: "Exhaust Clamp", slug: "exhaust-clamp", categorySlug: "exhaust" },
      { name: "Exhaust Gasket", slug: "exhaust-gasket", categorySlug: "exhaust" },
      { name: "Exhaust Header", slug: "exhaust-header", categorySlug: "exhaust" },
      { name: "Exhaust Manifold", slug: "exhaust-manifold", categorySlug: "exhaust" },
      { name: "Exhaust Tip", slug: "exhaust-tip", categorySlug: "exhaust" },
      { name: "Heat Shield", slug: "heat-shield", categorySlug: "exhaust" },
      { name: "Mid Pipe", slug: "mid-pipe", categorySlug: "exhaust" },
      { name: "Muffler", slug: "muffler", categorySlug: "exhaust" },
      { name: "Oxygen Sensor", slug: "oxygen-sensor" },
      { name: "Resonator", slug: "resonator", categorySlug: "exhaust" },
      { name: "Valved Exhaust", slug: "valved-exhaust", categorySlug: "exhaust" },
    ],
  },
  {
    name: "Forced Induction",
    slug: "forced-induction",
    description: "Turbo, supercharger, charge piping, boost control, and supporting air-charge parts.",
    categorySlug: "forced-induction",
    children: [
      { name: "Blow-Off Valve", slug: "blow-off-valve", categorySlug: "forced-induction" },
      { name: "Boost Controller", slug: "boost-controller", categorySlug: "forced-induction" },
      { name: "Charge Pipe", slug: "charge-pipe", categorySlug: "forced-induction" },
      { name: "Compressor Wheel", slug: "compressor-wheel", categorySlug: "forced-induction" },
      { name: "Intercooler Piping", slug: "intercooler-piping", categorySlug: "forced-induction" },
      { name: "Supercharger Kit", slug: "supercharger-kit", categorySlug: "forced-induction" },
      { name: "Turbo Blanket", slug: "turbo-blanket", categorySlug: "forced-induction" },
      { name: "Turbocharger", slug: "turbocharger", categorySlug: "forced-induction" },
      { name: "Turbocharger Kit", slug: "turbocharger-kit", categorySlug: "forced-induction" },
      { name: "Wastegate", slug: "wastegate", categorySlug: "forced-induction" },
    ],
  },
  {
    name: "Heat & Air Conditioning",
    slug: "heat-air-conditioning",
    description: "A/C, heater, blower, cabin filter, condenser, compressor, and HVAC controls.",
    children: [
      { name: "A/C Compressor", slug: "ac-compressor" },
      { name: "A/C Condenser", slug: "ac-condenser" },
      { name: "A/C Hose", slug: "ac-hose" },
      { name: "Blower Motor", slug: "blower-motor" },
      { name: "Cabin Air Filter", slug: "cabin-air-filter" },
      { name: "Evaporator Core", slug: "evaporator-core" },
      { name: "Heater Core", slug: "heater-core" },
      { name: "HVAC Control Module", slug: "hvac-control-module" },
    ],
  },
  {
    name: "Ignition",
    slug: "ignition",
    description: "Coils, spark plugs, ignition control, wires, and engine start ignition components.",
    children: [
      { name: "Distributor", slug: "distributor" },
      { name: "Ignition Coil", slug: "ignition-coil" },
      { name: "Ignition Control Module", slug: "ignition-control-module" },
      { name: "Ignition Switch", slug: "ignition-switch" },
      { name: "Spark Plug", slug: "spark-plug" },
      { name: "Spark Plug Wire", slug: "spark-plug-wire" },
    ],
  },
  {
    name: "Interior & Safety",
    slug: "interior-safety",
    description: "Seats, harnesses, cockpit trim, electronics, safety systems, and track interior parts.",
    categorySlug: "interior-safety",
    children: [
      { name: "Airbag Module", slug: "airbag-module" },
      { name: "Gauge", slug: "gauge" },
      { name: "Harness Bar", slug: "harness-bar", categorySlug: "interior-safety" },
      { name: "Racing Harness", slug: "racing-harness", categorySlug: "interior-safety" },
      { name: "Racing Seat", slug: "racing-seat", categorySlug: "interior-safety" },
      { name: "Roll Cage", slug: "roll-cage", categorySlug: "interior-safety" },
      { name: "Shift Knob", slug: "shift-knob", categorySlug: "interior-safety" },
      { name: "Short Shifter", slug: "short-shifter", categorySlug: "drivetrain" },
      { name: "Steering Wheel", slug: "steering-wheel", categorySlug: "interior-safety" },
    ],
  },
  {
    name: "Steering",
    slug: "steering",
    description: "Power steering, racks, tie rods, columns, pumps, and steering service parts.",
    children: [
      { name: "Power Steering Pump", slug: "power-steering-pump" },
      { name: "Power Steering Rack", slug: "power-steering-rack" },
      { name: "Steering Column", slug: "steering-column" },
      { name: "Steering Coupler", slug: "steering-coupler" },
      { name: "Steering Rack", slug: "steering-rack" },
      { name: "Tie Rod End", slug: "tie-rod-end", categorySlug: "suspension" },
    ],
  },
  {
    name: "Suspension",
    slug: "suspension",
    description: "Control arms, springs, dampers, coilovers, bushings, mounts, links, and alignment parts.",
    categorySlug: "suspension",
    children: [
      { name: "Air Suspension Kit", slug: "air-suspension-kit", categorySlug: "suspension" },
      { name: "Ball Joint", slug: "ball-joint", categorySlug: "suspension" },
      { name: "Camber Arm", slug: "camber-arm", categorySlug: "suspension" },
      { name: "Coil Spring", slug: "coil-spring", categorySlug: "suspension" },
      { name: "Coilover Kit", slug: "coilover-kit", categorySlug: "suspension" },
      { name: "Control Arm", slug: "control-arm", categorySlug: "suspension" },
      { name: "Lowering Spring", slug: "lowering-spring", categorySlug: "suspension" },
      { name: "Shock Absorber", slug: "shock-absorber", categorySlug: "suspension" },
      { name: "Sway Bar", slug: "sway-bar", categorySlug: "suspension" },
      { name: "Sway Bar Link", slug: "sway-bar-link", categorySlug: "suspension" },
      { name: "Strut", slug: "strut", categorySlug: "suspension" },
      { name: "Subframe Bushing", slug: "subframe-bushing", categorySlug: "suspension" },
    ],
  },
  {
    name: "Tire & Wheel",
    slug: "tire-wheel",
    description: "Wheels, tires, sensors, spacers, lug hardware, and track fitment components.",
    categorySlug: "wheels-tires",
    children: [
      { name: "Lug Bolt", slug: "lug-bolt", categorySlug: "wheels-tires" },
      { name: "Lug Nut", slug: "lug-nut", categorySlug: "wheels-tires" },
      { name: "Performance Tire", slug: "performance-tire", categorySlug: "wheels-tires" },
      { name: "Racing Wheel", slug: "racing-wheel", categorySlug: "wheels-tires" },
      { name: "Spacer", slug: "spacer", categorySlug: "wheels-tires" },
      { name: "TPMS Sensor", slug: "tpms-sensor", categorySlug: "wheels-tires" },
      { name: "Wheel", slug: "wheel", categorySlug: "wheels-tires" },
      { name: "Wheel Lock", slug: "wheel-lock", categorySlug: "wheels-tires" },
    ],
  },
  {
    name: "Tools & Garage",
    slug: "tools-garage",
    description: "Garage tools, diagnostic equipment, fluids, stands, lifts, and service supplies.",
    children: [
      { name: "Diagnostic Scanner", slug: "diagnostic-scanner", categorySlug: "ecu-tuning" },
      { name: "Engine Oil", slug: "engine-oil" },
      { name: "Jack Stand", slug: "jack-stand" },
      { name: "Torque Wrench", slug: "torque-wrench" },
      { name: "Transmission Fluid", slug: "transmission-fluid" },
      { name: "Wheel Chock", slug: "wheel-chock" },
    ],
  },
  {
    name: "Transmission",
    slug: "transmission",
    description: "Manual, automatic, dual-clutch, transaxle, clutch, seal, cooler, and control parts.",
    categorySlug: "drivetrain",
    children: [
      { name: "Clutch Kit", slug: "clutch-kit", categorySlug: "drivetrain" },
      { name: "Clutch Master Cylinder", slug: "clutch-master-cylinder", categorySlug: "drivetrain" },
      { name: "Clutch Slave Cylinder", slug: "clutch-slave-cylinder", categorySlug: "drivetrain" },
      { name: "DCT Service Kit", slug: "dct-service-kit", categorySlug: "drivetrain" },
      { name: "Shift Cable", slug: "shift-cable", categorySlug: "drivetrain" },
      { name: "Transmission Cooler", slug: "transmission-cooler", categorySlug: "cooling" },
      { name: "Transmission Filter", slug: "transmission-filter", categorySlug: "drivetrain" },
      { name: "Transmission Pan", slug: "transmission-pan", categorySlug: "drivetrain" },
      { name: "Transmission Seal", slug: "transmission-seal", categorySlug: "drivetrain" },
    ],
  },
  {
    name: "ECU, Data & Tuning",
    slug: "ecu-data-tuning",
    description: "ECU tuning, standalone computers, data logging, displays, sensors, and calibration tools.",
    categorySlug: "ecu-tuning",
    children: [
      { name: "Accessport", slug: "accessport", categorySlug: "ecu-tuning" },
      { name: "Data Logger", slug: "data-logger", categorySlug: "ecu-tuning" },
      { name: "ECU Calibration", slug: "ecu-calibration", categorySlug: "ecu-tuning" },
      { name: "Flex Fuel Sensor", slug: "flex-fuel-sensor", categorySlug: "fueling" },
      { name: "Piggyback Tuner", slug: "piggyback-tuner", categorySlug: "ecu-tuning" },
      { name: "Standalone ECU", slug: "standalone-ecu", categorySlug: "ecu-tuning" },
      { name: "Wideband Oxygen Sensor", slug: "wideband-oxygen-sensor", categorySlug: "ecu-tuning" },
    ],
  },
];
