import { PrismaClient } from "@prisma/client";
import { toPartSlug } from "@/lib/parts/slug";

const prisma = new PrismaClient();

type SourcePartSeed = {
  name: string;
  brandSlug: string;
  categorySlug: string;
  sourceName: string;
  sourceUrl: string;
  imageUrl?: string;
  partNumber?: string;
  description: string;
  status?: "ACTIVE" | "MANUAL_REVIEW";
  retailPriceCents?: number;
  estimatedHpGain?: number;
  estimatedTorqueGain?: number;
  gainBasis?: string;
  installComplexity?: "DIY" | "SHOP_RECOMMENDED" | "PRO_ONLY";
  compatibility: Array<{
    makeSlug: string;
    modelSlug?: string;
    yearStart?: number;
    yearEnd?: number;
    trim?: string;
    engine?: string;
    notes?: string;
  }>;
};

const REAL_PART_BATCH: SourcePartSeed[] = [
  {
    name: "Lamborghini Huracan Intake System",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/lamborghini-huracan/",
    partNumber: "EVE-HCN-CF-INT",
    description: "Carbon intake system for Lamborghini Huracan V10 models with sealed airflow housings and tune-aware MAF behavior.",
    status: "ACTIVE",
    estimatedHpGain: 12,
    gainBasis: "Source states 12-15 hp gain; stored conservatively at the low end.",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "lamborghini", modelSlug: "huracan", yearStart: 2014, trim: "V10" },
      { makeSlug: "lamborghini", modelSlug: "hurac-n-lp-610-4", yearStart: 2014, trim: "LP 610-4" },
    ],
  },
  {
    name: "Slip-On Line Titanium Exhaust - Huracan",
    brandSlug: "akrapovic",
    categorySlug: "exhaust",
    sourceName: "STM Tuned / Akrapovic",
    sourceUrl: "https://stmtuned.com/products/mtplati2-akrapovic-titanium-slip-on-exhaust-huracan",
    imageUrl: "https://stmtuned.com/cdn/shop/products/MTPLATI2-akrapovic-titanium-slip-on-exhaust-huracan-1_1024x1024.jpg?v=1617819896",
    partNumber: "MTP-LA/TI/2",
    description: "Titanium slip-on exhaust system for Lamborghini Huracan fitments published by Akrapovic.",
    status: "ACTIVE",
    retailPriceCents: 1328105,
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "lamborghini", modelSlug: "huracan", yearStart: 2014, trim: "LP 580-2 / LP 610-4" },
      { makeSlug: "lamborghini", modelSlug: "hurac-n-lp-610-4", yearStart: 2014, trim: "LP 610-4" },
    ],
  },
  {
    name: "Slip-On Line Titanium Exhaust - Aventador",
    brandSlug: "akrapovic",
    categorySlug: "exhaust",
    sourceName: "STM Tuned / Akrapovic",
    sourceUrl: "https://stmtuned.com/products/mtplati1-akrapovic-titanium-slip-on-exhaust-aventador",
    imageUrl: "https://stmtuned.com/cdn/shop/products/MTPLATI1-akrapovic-titanium-slip-on-exhaust-aventador-1_1024x1024.jpg?v=1617814950",
    partNumber: "MTP-LA/TI/1",
    description: "Titanium slip-on exhaust system for Lamborghini Aventador LP 700-4 applications.",
    status: "ACTIVE",
    estimatedHpGain: 10,
    gainBasis: "Source states a 9.9 hp gain; stored as the nearest whole horsepower.",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "lamborghini", modelSlug: "aventador", yearStart: 2011, trim: "LP 700-4" },
      { makeSlug: "lamborghini", modelSlug: "aventador-lp-700-4", yearStart: 2011 },
    ],
  },
  {
    name: "Ferrari F12 Carbon Intake System",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/ferrari-f12-berlinetta/",
    partNumber: "EVE-F12-CF-INT",
    description: "Carbon intake system for Ferrari F12 Berlinetta with carbon airbox lids and high-flow panel filters.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "ferrari", modelSlug: "f12berlinetta", yearStart: 2012, yearEnd: 2017 },
    ],
  },
  {
    name: "Ferrari F12/812SF/812GTS Valved Exhaust",
    brandSlug: "capristo",
    categorySlug: "exhaust",
    sourceName: "Capristo Exhaust",
    sourceUrl: "https://capristoexhaust.com/collections/ferrari-f12",
    description: "Valved exhaust listing from Capristo for Ferrari F12 and 812-family applications.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "ferrari", modelSlug: "f12berlinetta", yearStart: 2012, yearEnd: 2017 },
      { makeSlug: "ferrari", modelSlug: "812-superfast", yearStart: 2017, trim: "812 Superfast / GTS" },
    ],
  },
  {
    name: "GR Supra Super Turbo Muffler Urban Matte Edition",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/pickup-car/gr_supra/index.html",
    partNumber: "31029-AT013",
    description: "HKS Super Turbo Muffler Urban Matte Edition for GR Supra RZ 3.0-liter B58 manual fitment.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "toyota", modelSlug: "gr-supra-rz", yearStart: 2020, trim: "RZ 6MT", engine: "B58" },
    ],
  },
  {
    name: "GR Supra Dry Carbon Racing Suction",
    brandSlug: "hks",
    categorySlug: "intake",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/intake/db/21926",
    partNumber: "70028-AT001",
    description: "Dry carbon racing suction intake pipe for Toyota GR Supra 3.0-liter B58 applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "toyota", modelSlug: "gr-supra-rz", yearStart: 2020, engine: "B58" },
    ],
  },
  {
    name: "GR Supra Power Editor Vehicle Specific Kit",
    brandSlug: "hks",
    categorySlug: "ecu-tuning",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/electronics/db/29932",
    partNumber: "42018-AT016",
    description: "Plug-in boost control and calibration device for Toyota GR Supra 3.0-liter B58 fitments.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "toyota", modelSlug: "gr-supra-rz", yearStart: 2020, engine: "B58" },
    ],
  },
  {
    name: "GT800 Full Turbine Kit",
    brandSlug: "hks",
    categorySlug: "forced-induction",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/turbo/db/13909",
    partNumber: "11003-AN012",
    description: "HKS GT800 full turbine kit for R35 GT-R applications using the VR38DETT platform.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "gt-r", yearStart: 2008, trim: "R35", engine: "VR38DETT" },
      { makeSlug: "nissan", modelSlug: "gt-r-nismo", yearStart: 2008, trim: "R35", engine: "VR38DETT" },
    ],
  },
  {
    name: "Street Advance Z Coilover Kit - Acura RSX",
    brandSlug: "tein",
    categorySlug: "suspension",
    sourceName: "TEIN USA",
    sourceUrl: "https://www.kseriesparts.com/TEI-GSA28-9USS2.html",
    imageUrl: "https://www.kseriesparts.com/graphics/00000001/TEI-GSA28-9USS2.jpg",
    partNumber: "GSA28-9USS2",
    description: "TEIN Street Advance Z coilover kit application for Acura RSX model years.",
    status: "ACTIVE",
    retailPriceCents: 85008,
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "acura", modelSlug: "rsx", yearStart: 2002, yearEnd: 2006 },
      { makeSlug: "acura", modelSlug: "rsx-type-s", yearStart: 2002, yearEnd: 2006 },
    ],
  },
  {
    name: "Flex Z Coilover Kit - Acura RSX",
    brandSlug: "tein",
    categorySlug: "suspension",
    sourceName: "TEIN USA",
    sourceUrl: "https://www.proimporttuners.com/parts/acura/rsx-tein-flex-z-full-coilovers.html",
    imageUrl: "https://www.proimporttuners.com/images/spd/prod/619/mh-1500/62202.webp",
    description: "TEIN Flex Z coilover kit application for late Acura RSX fitments.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "acura", modelSlug: "rsx", yearStart: 2005, yearEnd: 2006 },
      { makeSlug: "acura", modelSlug: "rsx-type-s", yearStart: 2005, yearEnd: 2006 },
    ],
  },
  {
    name: "Honda Civic FK8 Type R Carbon Intake",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/honda-civic-fk8-type-r/",
    partNumber: "EVE-FK8-CF-INT",
    description: "Eventuri carbon intake system for the FK8 Honda Civic Type R with sealed airbox, high-flow filter, and carbon Venturi stack.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "honda", modelSlug: "civic-type-r", yearStart: 2017, yearEnd: 2021, engine: "K20C" },
      { makeSlug: "honda", modelSlug: "civic-type-r-limited-edition-fk8", yearStart: 2021, yearEnd: 2021, engine: "K20C" },
    ],
  },
  {
    name: "Honda Civic FL5 Type R Carbon Intake",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/honda-civic-fl5-type-r/",
    partNumber: "EVE-FL5-CF-INT",
    description: "Eventuri carbon intake system for the FL5 Civic Type R with a sealed airbox designed to reduce heat soak.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "honda", modelSlug: "civic-type-r-fl5", yearStart: 2023, engine: "K20C" },
    ],
  },
  {
    name: "Honda FK8 Carbon Turbo Tube V3",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/honda-fk8-turbo-tube-v3/",
    description: "Eventuri carbon turbo tube for FK8 Civic Type R applications with enlarged volume for reduced turbo restriction.",
    status: "ACTIVE",
    estimatedHpGain: 9,
    estimatedTorqueGain: 9,
    gainBasis: "Source states 9 hp and 9 ft-lb peak gains.",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "honda", modelSlug: "civic-type-r", yearStart: 2017, yearEnd: 2021, engine: "K20C" },
      { makeSlug: "honda", modelSlug: "civic-type-r-limited-edition-fk8", yearStart: 2021, yearEnd: 2021, engine: "K20C" },
    ],
  },
  {
    name: "Honda FK2 Carbon Turbo Tube V3",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/honda-fk2-turbo-tube-v3/",
    description: "Eventuri carbon turbo tube for FK2 Civic Type R applications with revised airflow volume and MAF integration.",
    status: "ACTIVE",
    estimatedHpGain: 9,
    estimatedTorqueGain: 9,
    gainBasis: "Source states 9 hp and 9 ft-lb peak gains.",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "honda", modelSlug: "civic-type-r-fk2", yearStart: 2015, yearEnd: 2016, engine: "K20C" },
    ],
  },
  {
    name: "Porsche 991 GT3 RS Carbon Intake",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/porsche-991-gt3-rs/",
    description: "Eventuri carbon intake system for Porsche 991 GT3 RS applications using patented Venturi filter housings.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "porsche", modelSlug: "911-gt3-rs-991", yearStart: 2015, yearEnd: 2019 },
    ],
  },
  {
    name: "Toyota GR86 Carbon Intake",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/toyota-gr86/",
    description: "Eventuri carbon intake system for the Toyota GR86 platform with a carbon fiber intake path and high-flow filtration.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "toyota", modelSlug: "gr86-rz", yearStart: 2022, engine: "FA24" },
    ],
  },
  {
    name: "Toyota GR Yaris Carbon Intake",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/toyota-gr-yaris/",
    description: "Eventuri intake system for GR Yaris turbo applications designed around low intake temperatures and higher flow rate.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "toyota", modelSlug: "gr-yaris-rz-high-performance", yearStart: 2020, engine: "G16E-GTS" },
    ],
  },
  {
    name: "Civic Type R FL5 Hi-Power Exhaust",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/muffler/db/33938",
    description: "HKS Hi-Power exhaust system for FL5 Civic Type R applications with reduced exhaust pressure versus stock.",
    status: "ACTIVE",
    estimatedHpGain: 5,
    estimatedTorqueGain: 6,
    gainBasis: "Source states maximum increase of 3.6 kW and torque increase up to 7.5 Nm; stored as rounded imperial estimates.",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "honda", modelSlug: "civic-type-r-fl5", yearStart: 2023, engine: "K20C" },
    ],
  },
  {
    name: "Civic Type R FL5 Power Editor",
    brandSlug: "hks",
    categorySlug: "ecu-tuning",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/electronics/db/33087",
    partNumber: "42018-AH013",
    description: "HKS Power Editor boost control kit for the FL5 Civic Type R with preset boost increase data and bypass connector.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "honda", modelSlug: "civic-type-r-fl5", yearStart: 2023, engine: "K20C" },
    ],
  },
  {
    name: "Civic Type R FL5 R Type Intercooler",
    brandSlug: "hks",
    categorySlug: "cooling",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/cooling/db/33737",
    partNumber: "13001-AH008",
    description: "HKS R Type intercooler kit for FL5 Civic Type R with increased core area for sustained cooling under boost.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "honda", modelSlug: "civic-type-r-fl5", yearStart: 2023, engine: "K20C" },
    ],
  },
  {
    name: "Civic Type R FL5 GT Sports Turbine Kit",
    brandSlug: "hks",
    categorySlug: "forced-induction",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/turbo/db/33968",
    description: "HKS GT Sports Turbine Kit for FL5 Civic Type R, designed to maintain boost at high RPM.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "honda", modelSlug: "civic-type-r-fl5", yearStart: 2023, engine: "K20C" },
    ],
  },
  {
    name: "Civic Type R FK8 Hipermax R Coilovers",
    brandSlug: "hks",
    categorySlug: "suspension",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/hipermax/db/31703",
    imageUrl: "https://www.hks-power.co.jp/storage/syshks/product_db/7xxyYQJKgTRthYExUc0WnTNsce1o26ZLbdk97Oqw.jpg",
    partNumber: "80310-AH003",
    description: "HKS Hipermax R coilover kit for FK8 Civic Type R applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "honda", modelSlug: "civic-type-r", yearStart: 2017, yearEnd: 2021, engine: "K20C" },
      { makeSlug: "honda", modelSlug: "civic-type-r-limited-edition-fk8", yearStart: 2021, yearEnd: 2021, engine: "K20C" },
    ],
  },
  {
    name: "Civic Type R FL5 Hipermax S Coilovers",
    brandSlug: "hks",
    categorySlug: "suspension",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/hipermax/db/33300",
    description: "HKS Hipermax S suspension kit for FL5 Civic Type R, built for street comfort and sporty control.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "honda", modelSlug: "civic-type-r-fl5", yearStart: 2023, engine: "K20C" },
    ],
  },
  {
    name: "BRZ Hi-Power Spec-L II Exhaust",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/muffler/db/33896",
    description: "HKS Hi-Power Spec-L II exhaust for Subaru BRZ ZN6/ZC6 applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "subaru", modelSlug: "brz", yearStart: 2012, yearEnd: 2020 },
      { makeSlug: "subaru", modelSlug: "brz-s", yearStart: 2012, yearEnd: 2020 },
    ],
  },
  {
    name: "GT-R R35 R Type Intercooler",
    brandSlug: "hks",
    categorySlug: "cooling",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/cooling/db/11267",
    partNumber: "13001-AN013",
    description: "HKS R Type intercooler kit for Nissan GT-R R35 with large-capacity core and carbon air guide.",
    status: "ACTIVE",
    estimatedHpGain: 12,
    gainBasis: "Source comparison shows 608.6 ps with HKS intercooler versus 596.3 ps stock.",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "gt-r", yearStart: 2008, trim: "R35", engine: "VR38DETT" },
      { makeSlug: "nissan", modelSlug: "gt-r-nismo", yearStart: 2008, trim: "R35", engine: "VR38DETT" },
    ],
  },
  {
    name: "GT-R R35 GT5565 BB Full Turbine Kit",
    brandSlug: "hks",
    categorySlug: "forced-induction",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/turbo/db/36404",
    description: "HKS GT5565 BB full turbine kit for high-power Nissan GT-R R35 configurations.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "gt-r", yearStart: 2008, trim: "R35", engine: "VR38DETT" },
      { makeSlug: "nissan", modelSlug: "gt-r-nismo", yearStart: 2008, trim: "R35", engine: "VR38DETT" },
    ],
  },
  {
    name: "GT-R R35 Turbine Suction Kit",
    brandSlug: "hks",
    categorySlug: "intake",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/turbo/db/36406",
    description: "HKS turbine suction kit for R35 GT-R turbo applications using D70 mm silicone hose and dual-layer wet filters.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "gt-r", yearStart: 2008, trim: "R35", engine: "VR38DETT" },
      { makeSlug: "nissan", modelSlug: "gt-r-nismo", yearStart: 2008, trim: "R35", engine: "VR38DETT" },
    ],
  },
  {
    name: "Ferrari 296 GTB Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/ferrari/296/296-gtb/",
    description: "NOVITEC Ferrari 296 GTB performance exhaust and sports catalyst program.",
    status: "ACTIVE",
    estimatedHpGain: 38,
    gainBasis: "Source states an additional 38 horsepower with turbo inlets, exhaust, and sports catalysts.",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "ferrari", modelSlug: "296-gtb", yearStart: 2022 },
      { makeSlug: "ferrari", modelSlug: "296-gtb-gts", yearStart: 2022 },
    ],
  },
  {
    name: "Ferrari F8 Tributo Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/ferrari/f8/f8-tributo/",
    description: "NOVITEC Ferrari F8 Tributo performance range including high-performance exhaust, suspension, wheels, and aerodynamic components.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "ferrari", modelSlug: "f8-tributo", yearStart: 2020 },
    ],
  },
  {
    name: "Lamborghini Revuelto Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/lamborghini/revuelto/",
    description: "NOVITEC Lamborghini Revuelto refinement program focused on V12 acoustic character, exhaust, stance, and carbon components.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "lamborghini", modelSlug: "revuelto", yearStart: 2024 },
    ],
  },
  {
    name: "McLaren Artura High-Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/mclaren/artura/",
    description: "NOVITEC McLaren Artura high-performance exhaust program with optional Inconel construction.",
    status: "ACTIVE",
    estimatedHpGain: 35,
    gainBasis: "Source states about 26 kW / 35 hp added to the twin-turbo V6 internal-combustion engine.",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "mclaren", modelSlug: "artura", yearStart: 2023 },
    ],
  },
  {
    name: "McLaren 765LT Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/mclaren/765lt-2/765lt/",
    description: "NOVITEC McLaren 765LT performance exhaust, aero, wheels, and suspension range for the Longtail platform.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "mclaren", modelSlug: "765lt", yearStart: 2021 },
    ],
  },
  {
    name: "RX-7 FD3S Super Turbo Muffler",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/muffler/db/12776",
    partNumber: "31029-AZ001",
    description: "HKS Super Turbo Muffler for Mazda RX-7 FD3S 13B-REW applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "mazda", modelSlug: "rx-7", yearStart: 1991, yearEnd: 2002, engine: "13B-REW" },
      { makeSlug: "mazda", modelSlug: "rx-7-spirit-r-type-a-fd", yearStart: 1991, yearEnd: 2002, engine: "13B-REW" },
      { makeSlug: "mazda", modelSlug: "fini-rx-7-type-r-fd", yearStart: 1991, yearEnd: 2002, engine: "13B-REW" },
    ],
  },
  {
    name: "RX-7 FD3S Silent Hi-Power Exhaust",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/muffler/db/361",
    partNumber: "31019-AZ002",
    description: "HKS Silent Hi-Power exhaust for earlier Mazda RX-7 FD3S 13B-REW fitments.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "mazda", modelSlug: "rx-7", yearStart: 1991, yearEnd: 1998, engine: "13B-REW" },
      { makeSlug: "mazda", modelSlug: "fini-rx-7-type-r-fd", yearStart: 1991, yearEnd: 1998, engine: "13B-REW" },
    ],
  },
  {
    name: "Lancer Evolution IX R Type Intercooler",
    brandSlug: "hks",
    categorySlug: "cooling",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/cooling/db/8926",
    description: "HKS R Type intercooler kit for Lancer Evolution IX with lightweight core and short piping layout.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "mitsubishi", modelSlug: "lancer-evolution-ix", yearStart: 2005, yearEnd: 2007, engine: "4G63" },
      { makeSlug: "mitsubishi", modelSlug: "lancer-evolution-ix-mr-gsr", yearStart: 2005, yearEnd: 2007, engine: "4G63" },
    ],
  },
  {
    name: "Lancer Evolution X R Type Intercooler",
    brandSlug: "hks",
    categorySlug: "cooling",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/cooling/db/10306",
    imageUrl: "https://www.hks-power.co.jp/storage/syshks/product_db/APuSV3NLZiE7GTr1WCdKq0Rl1VRW8UqwUk93F4Km.jpeg",
    description: "HKS R Type intercooler kit for Lancer Evolution X with larger low-pressure-loss core and 70 mm piping spec.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "mitsubishi", modelSlug: "lancer-evolution-final", yearStart: 2008, yearEnd: 2015, engine: "4B11T" },
      { makeSlug: "mitsubishi", modelSlug: "lancer-evolution", yearStart: 2008, yearEnd: 2015, engine: "4B11T" },
    ],
  },
  {
    name: "Lancer Evolution IX GT III Sports Turbine Kit",
    brandSlug: "hks",
    categorySlug: "forced-induction",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/turbo/db/20283",
    description: "HKS GT III Sports Turbine Kit for Lancer Evolution IX 4G63 high-power applications.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "mitsubishi", modelSlug: "lancer-evolution-ix", yearStart: 2005, yearEnd: 2007, engine: "4G63" },
      { makeSlug: "mitsubishi", modelSlug: "lancer-evolution-ix-mr-gsr", yearStart: 2005, yearEnd: 2007, engine: "4G63" },
    ],
  },
  {
    name: "Lancer Evolution X GT II Sports Turbine Kit",
    brandSlug: "hks",
    categorySlug: "forced-induction",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/turbo/db/12540",
    description: "HKS GT II Sports Turbine Kit for Lancer Evolution X with ball-bearing stock replacement turbo design.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "mitsubishi", modelSlug: "lancer-evolution-final", yearStart: 2008, yearEnd: 2015, engine: "4B11T" },
      { makeSlug: "mitsubishi", modelSlug: "lancer-evolution", yearStart: 2008, yearEnd: 2015, engine: "4B11T" },
    ],
  },
  {
    name: "WRX STI Hipermax R Coilovers",
    brandSlug: "hks",
    categorySlug: "suspension",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/hipermax/db/31700",
    description: "HKS Hipermax R suspension kit for Subaru Impreza WRX STI applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "subaru", modelSlug: "wrx-sti", yearStart: 2015, yearEnd: 2021, engine: "EJ25" },
      { makeSlug: "subaru", modelSlug: "impreza-wrx-sti", yearStart: 2000, yearEnd: 2014, engine: "EJ20 / EJ25" },
    ],
  },
  {
    name: "WRX STI Hipermax S Coilovers",
    brandSlug: "hks",
    categorySlug: "suspension",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/hipermax/db/31689",
    description: "HKS Hipermax S suspension kit for Subaru WRX STI street and sports use.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "subaru", modelSlug: "wrx-sti", yearStart: 2015, yearEnd: 2021, engine: "EJ25" },
    ],
  },
  {
    name: "Silvia S15 Super Turbo Muffler",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/muffler/db/13177",
    partNumber: "31029-AN004",
    description: "HKS Super Turbo Muffler for Nissan Silvia S15 SR20DET fitments.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "silvia-s15", yearStart: 1999, yearEnd: 2002, engine: "SR20DET" },
      { makeSlug: "nissan", modelSlug: "silvia-spec-r-aero-s15", yearStart: 1999, yearEnd: 2002, engine: "SR20DET" },
    ],
  },
  {
    name: "Silvia S15 Racing Suction Intake",
    brandSlug: "hks",
    categorySlug: "intake",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/intake/db/18106",
    partNumber: "70020-AN101",
    description: "HKS Racing Suction intake for Nissan Silvia S15 SR20DET applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "silvia-s15", yearStart: 1999, yearEnd: 2002, engine: "SR20DET" },
      { makeSlug: "nissan", modelSlug: "silvia-spec-r-aero-s15", yearStart: 1999, yearEnd: 2002, engine: "SR20DET" },
    ],
  },
  {
    name: "Silvia S15 GT III Sports Turbine Kit",
    brandSlug: "hks",
    categorySlug: "forced-induction",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/turbo/db/17757",
    partNumber: "11004-AN013",
    description: "HKS GT III Sports Turbine Kit for Nissan Silvia S15 and S14 SR20DET platforms.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "silvia-s15", yearStart: 1999, yearEnd: 2002, engine: "SR20DET" },
      { makeSlug: "nissan", modelSlug: "silvia-spec-r-aero-s15", yearStart: 1999, yearEnd: 2002, engine: "SR20DET" },
      { makeSlug: "nissan", modelSlug: "silvia-s14", yearStart: 1993, yearEnd: 1998, engine: "SR20DET" },
    ],
  },
  {
    name: "Silvia S15 Hipermax R Coilovers",
    brandSlug: "hks",
    categorySlug: "suspension",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/hipermax/db/31707",
    description: "HKS Hipermax R coilover kit for Nissan Silvia S15 chassis applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "silvia-s15", yearStart: 1999, yearEnd: 2002 },
      { makeSlug: "nissan", modelSlug: "silvia-spec-r-aero-s15", yearStart: 1999, yearEnd: 2002 },
    ],
  },
  {
    name: "Mercedes-AMG GT R Carbon Intake",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/mercedes-amg-gtr-gts-gt/",
    description: "Eventuri sealed carbon intake system for Mercedes-AMG GT R, GT S, and GT applications using patented Venturi housings.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "amg", modelSlug: "mercedes-amg-gt-r", yearStart: 2017, engine: "M178" },
      { makeSlug: "amg", modelSlug: "mercedes-amg-gt-s", yearStart: 2015, engine: "M178" },
    ],
  },
  {
    name: "Mercedes-AMG GT R ECU Upgrade",
    brandSlug: "renntech",
    categorySlug: "ecu-tuning",
    sourceName: "RENNtech",
    sourceUrl: "https://store.renntechmercedes.com/products/renntech-ecu-upgrade-c190-amg-gt-r-659hp-614lb-ft-4-0l-v8-biturbo-m178",
    description: "RENNtech ECU upgrade for C190 Mercedes-AMG GT R M178 4.0-liter V8 biturbo applications.",
    status: "ACTIVE",
    retailPriceCents: 328000,
    estimatedHpGain: 50,
    estimatedTorqueGain: 73,
    gainBasis: "Source states up to +50 hp and +73 lb-ft.",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "amg", modelSlug: "mercedes-amg-gt-r", yearStart: 2018, engine: "M178" },
    ],
  },
  {
    name: "Mercedes-AMG GT R R1 Performance Package",
    brandSlug: "renntech",
    categorySlug: "ecu-tuning",
    sourceName: "RENNtech",
    sourceUrl: "https://store.renntechmercedes.com/products/renntech-r1-pkg-c190-amg-gt-r-669hp-624lb-ft-4-0l-v8-biturbo-m178-my2018",
    description: "RENNtech R1 package for AMG GT R with ECU tune, BOV adapters, high-flow air filters, and stainless steel downpipes.",
    status: "ACTIVE",
    estimatedHpGain: 60,
    estimatedTorqueGain: 83,
    gainBasis: "Source states R1 package gains up to +60 hp and +83 lb-ft.",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "amg", modelSlug: "mercedes-amg-gt-r", yearStart: 2018, engine: "M178" },
    ],
  },
  {
    name: "Audi R8 GTC-500 Adjustable Wing",
    brandSlug: "apr-performance",
    categorySlug: "aero-body",
    sourceName: "APR Performance",
    sourceUrl: "https://shop.aprperformance.com/products/audi-r8-gtc-500-71-adjustable-wing-with-carbon-fiber-active-spoiler-panel-replacement-2016-up",
    description: "APR Performance GTC-500 adjustable carbon wing and trunk panel replacement for 2016-up Audi R8 applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "audi", modelSlug: "r8-coup-v10-plus", yearStart: 2016, yearEnd: 2022 },
    ],
  },
  {
    name: "Audi R8 GTC-500 Adjustable Wing 2006-2014",
    brandSlug: "apr-performance",
    categorySlug: "aero-body",
    sourceName: "APR Performance",
    sourceUrl: "https://shop.aprperformance.com/products/audi-r8-gtc-500-71-adjustable-wing-2006-14",
    description: "APR Performance GTC-500 adjustable carbon wing for first-generation Audi R8 applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "audi", modelSlug: "r8-4-2", yearStart: 2006, yearEnd: 2014 },
    ],
  },
  {
    name: "BMW F87 M2 Competition Carbon Intake",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/bmw-f87-m2-competition/",
    description: "Eventuri intake system for BMW F87 M2 Competition applications with sealed ducts and patented Venturi filter housings.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "bmw", modelSlug: "m2-competition", yearStart: 2018, yearEnd: 2021, engine: "S55" },
    ],
  },
  {
    name: "BMW E36 M3 Carbon Intake",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/bmw-e36-m3/",
    description: "Eventuri intake for BMW E36 M3 applications, developed around a continuous laminar path from filter to intake plenum.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "bmw", modelSlug: "m3-e36", yearStart: 1992, yearEnd: 1999 },
      { makeSlug: "bmw", modelSlug: "3-series-e36", yearStart: 1992, yearEnd: 1999 },
    ],
  },
  {
    name: "BMW G8X Carbon Fiber Cold Air Intake",
    brandSlug: "dinan",
    categorySlug: "intake",
    sourceName: "Dinan",
    sourceUrl: "https://www.dinancars.com/products/intake-systems/intake-kits/parts/D760-0063",
    imageUrl: "https://images.dinancars.com/583x/6686377e7aba0fc8d6596dd517863b12c4d5fbf4.jpg",
    partNumber: "D760-0063",
    description: "Dinan gloss carbon fiber cold air intake for late-model BMW M2, M3, and M4 applications.",
    status: "ACTIVE",
    estimatedHpGain: 0,
    gainBasis: "Source emphasizes airflow capacity rather than a standalone horsepower claim.",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "bmw", modelSlug: "m3", yearStart: 2021, yearEnd: 2026 },
      { makeSlug: "bmw", modelSlug: "m4", yearStart: 2021, yearEnd: 2026 },
      { makeSlug: "bmw", modelSlug: "m2-competition", yearStart: 2021, yearEnd: 2026 },
    ],
  },
  {
    name: "Corvette C8 Intake System",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/c8-chevrolet-corvette/",
    description: "Eventuri carbon double Venturi filter housing intake system for Chevrolet Corvette C8 applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "chevrolet", modelSlug: "corvette-c8", yearStart: 2020 },
    ],
  },
  {
    name: "Corvette C8 Carbon Fiber Aero Kit",
    brandSlug: "apr-performance",
    categorySlug: "aero-body",
    sourceName: "APR Performance",
    sourceUrl: "https://shop.aprperformance.com/products/chevrolet-corvette-c8-aero-kit-2020-up",
    partNumber: "AB-208008",
    description: "APR Performance carbon fiber aero kit for Chevrolet Corvette C8 Stingray applications.",
    status: "ACTIVE",
    retailPriceCents: 493200,
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "chevrolet", modelSlug: "corvette-c8", yearStart: 2020 },
    ],
  },
  {
    name: "Corvette C8 GTC-500 Adjustable Wing",
    brandSlug: "apr-performance",
    categorySlug: "aero-body",
    sourceName: "APR Performance",
    sourceUrl: "https://shop.aprperformance.com/products/chevrolet-corvette-c8-gtc-500-adjustable-wing-2020-up",
    description: "APR Performance GTC-500 adjustable carbon wing for Chevrolet Corvette C8 applications.",
    status: "ACTIVE",
    retailPriceCents: 265000,
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "chevrolet", modelSlug: "corvette-c8", yearStart: 2020 },
    ],
  },
  {
    name: "Camaro ZL1 1LE Carbon Fiber Front Wind Splitter",
    brandSlug: "apr-performance",
    categorySlug: "aero-body",
    sourceName: "APR Performance",
    sourceUrl: "https://shop.aprperformance.com/products/chevrolet-camaro-zl1-1le-front-wind-splitter-2017-up",
    partNumber: "CW-601821",
    description: "APR Performance carbon fiber front wind splitter for 2017-2024 Chevrolet Camaro ZL1 1LE applications.",
    status: "ACTIVE",
    retailPriceCents: 65300,
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "chevrolet", modelSlug: "camaro-zl1-1le-package", yearStart: 2017, yearEnd: 2024 },
    ],
  },
  {
    name: "Dodge Challenger Hellcat Front Wind Splitter",
    brandSlug: "apr-performance",
    categorySlug: "aero-body",
    sourceName: "APR Performance",
    sourceUrl: "https://shop.aprperformance.com/products/dodge-challenger-hellcat-front-wind-splitter-2015-2023-apr-lip",
    description: "APR Performance carbon fiber front wind splitter for Dodge Challenger Hellcat applications.",
    status: "ACTIVE",
    retailPriceCents: 56000,
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "dodge", modelSlug: "challenger-srt-demon", yearStart: 2015, yearEnd: 2023 },
      { makeSlug: "dodge", modelSlug: "challenger-r-t", yearStart: 2015, yearEnd: 2023 },
    ],
  },
  {
    name: "Dodge Charger Widebody Front Wind Splitter",
    brandSlug: "apr-performance",
    categorySlug: "aero-body",
    sourceName: "APR Performance",
    sourceUrl: "https://shop.aprperformance.com/products/dodge-charger-widebody-front-wind-splitter-2020-2023",
    description: "APR Performance carbon fiber front wind splitter for Dodge Charger Scat Pack Widebody and Hellcat Widebody applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "dodge", modelSlug: "charger-srt-hellcat", yearStart: 2020, yearEnd: 2023 },
    ],
  },
  {
    name: "Dodge Viper SRT-10 Front Wind Splitter",
    brandSlug: "apr-performance",
    categorySlug: "aero-body",
    sourceName: "APR Performance",
    sourceUrl: "https://shop.aprperformance.com/products/dodge-viper-srt-8-honeycomb-front-wind-splitter-2003-2010",
    partNumber: "HCW-708206",
    description: "APR Performance carbon fiber honeycomb front wind splitter for 2003-2010 Dodge Viper SRT-10 coupe and convertible applications.",
    status: "ACTIVE",
    retailPriceCents: 121200,
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "dodge", modelSlug: "viper-srt10-coupe", yearStart: 2003, yearEnd: 2010 },
    ],
  },
  {
    name: "Dodge Viper Gen 5 GTC-500 Adjustable Wing",
    brandSlug: "apr-performance",
    categorySlug: "aero-body",
    sourceName: "APR Performance",
    sourceUrl: "https://shop.aprperformance.com/products/dodge-viper-gen-5-gtc-500-adjustable-wing-2013-2017",
    partNumber: "AS-107106PPF",
    description: "APR Performance GTC-500 adjustable carbon wing for 2013-2017 Dodge Viper Gen 5 applications.",
    status: "ACTIVE",
    retailPriceCents: 291000,
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "dodge", modelSlug: "viper-gts", yearStart: 2013, yearEnd: 2017 },
    ],
  },
  {
    name: "S2000 AP1/AP2 Hipermax R Coilovers",
    brandSlug: "hks",
    categorySlug: "suspension",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/hipermax/db/31849",
    description: "HKS Hipermax R suspension kit for Honda S2000 AP1 and AP2 chassis applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "honda", modelSlug: "s2000", yearStart: 1999, yearEnd: 2009, engine: "F20C / F22C" },
    ],
  },
  {
    name: "Nissan Z RZ34 Power Editor R Kit",
    brandSlug: "hks",
    categorySlug: "ecu-tuning",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/electronics/db/36337",
    partNumber: "42018-AN003",
    description: "HKS Power Editor R vehicle-specific boost controller kit for Nissan Z RZ34 VR30DDTT applications.",
    status: "ACTIVE",
    estimatedHpGain: 65,
    estimatedTorqueGain: 80,
    gainBasis: "Source states a 48 kW power difference and 109 Nm torque difference in the midrange; converted approximately.",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "z-performance", yearStart: 2023, engine: "VR30DDTT" },
      { makeSlug: "nissan", modelSlug: "fairlady-z-z34", yearStart: 2023, engine: "VR30DDTT", notes: "RZ34 Nissan Z / Fairlady Z platform." },
    ],
  },
  {
    name: "Nissan Z RZ34 Full Dual Muffler",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/muffler/db/33081",
    partNumber: "31014-KN002",
    description: "HKS Full Dual Muffler for Nissan Z RZ34 with D60.5 mm dual layout and selectable sound behavior.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "z-performance", yearStart: 2023, engine: "VR30DDTT" },
      { makeSlug: "nissan", modelSlug: "fairlady-z-z34", yearStart: 2023, engine: "VR30DDTT", notes: "RZ34 Nissan Z / Fairlady Z platform." },
    ],
  },
  {
    name: "GR Corolla Cold Air Intake Full Kit",
    brandSlug: "hks",
    categorySlug: "intake",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/intake/db/33906",
    partNumber: "70026-AT018",
    description: "HKS cold air intake full kit for GR Corolla G16E-GTS applications with enclosed intake air routing.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "toyota", modelSlug: "gr-corolla", yearStart: 2023, engine: "G16E-GTS" },
      { makeSlug: "toyota", modelSlug: "gr-corolla-morizo-edition", yearStart: 2023, engine: "G16E-GTS" },
    ],
  },
  {
    name: "GR Corolla Legamax Sports Exhaust",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/muffler/db/33370",
    partNumber: "31021-AT009",
    description: "HKS Legamax Sports exhaust for GR Corolla GZEA14H with valve-less dual-tail layout.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "toyota", modelSlug: "gr-corolla", yearStart: 2023, yearEnd: 2025, engine: "G16E-GTS" },
      { makeSlug: "toyota", modelSlug: "gr-corolla-morizo-edition", yearStart: 2023, yearEnd: 2025, engine: "G16E-GTS" },
    ],
  },
  {
    name: "GR Yaris Super Turbo Muffler Urban Matte Edition",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/muffler/db/33935",
    partNumber: "31029-AT018",
    description: "HKS Super Turbo Muffler Urban Matte Edition for GR Yaris G16E-GTS applications.",
    status: "ACTIVE",
    estimatedHpGain: 2,
    estimatedTorqueGain: 3,
    gainBasis: "Source comparison shows 279.4 PS versus 277.0 PS stock and 398.2 Nm versus 394.3 Nm stock.",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "toyota", modelSlug: "gr-yaris-rz-high-performance", yearStart: 2024, engine: "G16E-GTS" },
    ],
  },
  {
    name: "GR86 GT2 Supercharger Pro Kit",
    brandSlug: "hks",
    categorySlug: "forced-induction",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/supercharger/db/31835",
    description: "HKS GT2 supercharger pro kit for Toyota GR86 and related FA24 applications.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "toyota", modelSlug: "gr86-rz", yearStart: 2022, engine: "FA24" },
    ],
  },
  {
    name: "RX-8 Hi-Power Exhaust",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS USA",
    sourceUrl: "https://hksusa.com/product/31006-BZ001",
    imageUrl: "https://cheerful-bouquet-91c8f27a22.media.strapiapp.com/cat_06_05_31006_BZ_001_d0c3d1c74f.jpg",
    partNumber: "31006-BZ001",
    description: "HKS Hi-Power exhaust for Mazda RX-8 SE chassis applications.",
    status: "ACTIVE",
    retailPriceCents: 86000,
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "mazda", modelSlug: "rx-8", yearStart: 2004, yearEnd: 2008, engine: "13B-MSP" },
      { makeSlug: "mazda", modelSlug: "rx-8-spirit-r", yearStart: 2004, yearEnd: 2008, engine: "13B-MSP" },
    ],
  },
  {
    name: "RX-8 Metal Catalyzer",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/exhaust/db/4609",
    description: "HKS metal catalyzer for Mazda RX-8 with SUS304 stainless pipe construction.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "mazda", modelSlug: "rx-8", yearStart: 2003, yearEnd: 2012, engine: "13B-MSP" },
      { makeSlug: "mazda", modelSlug: "rx-8-spirit-r", yearStart: 2003, yearEnd: 2012, engine: "13B-MSP" },
    ],
  },
  {
    name: "Roadster ND Hipermax R Coilovers",
    brandSlug: "hks",
    categorySlug: "suspension",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/hipermax/db/36205",
    description: "HKS Hipermax R coilover kit for Mazda Roadster and MX-5 ND chassis applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "mazda", modelSlug: "roadster-s-nd", yearStart: 2015 },
      { makeSlug: "mazda", modelSlug: "roadster-nr-a-nd", yearStart: 2015 },
      { makeSlug: "mazda", modelSlug: "mx-5-miata", yearStart: 2015 },
      { makeSlug: "mazda", modelSlug: "miata", yearStart: 2015 },
    ],
  },
  {
    name: "Impreza WRX STI Super Turbo Muffler",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/muffler/db/17922",
    partNumber: "31029-AF014",
    description: "HKS Super Turbo Muffler for Subaru Impreza WRX STI GVB applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "subaru", modelSlug: "impreza-wrx-sti", yearStart: 2010, yearEnd: 2014, engine: "EJ20" },
      { makeSlug: "subaru", modelSlug: "impreza-sedan-wrx-sti", yearStart: 2010, yearEnd: 2014, engine: "EJ20" },
    ],
  },
  {
    name: "Impreza WRX STI Hipermax S Coilovers",
    brandSlug: "hks",
    categorySlug: "suspension",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/hipermax/db/31673",
    description: "HKS Hipermax S coilover kit for Subaru Impreza WRX STI applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "subaru", modelSlug: "impreza-wrx-sti", yearStart: 2000, yearEnd: 2014 },
      { makeSlug: "subaru", modelSlug: "impreza-sedan-wrx-sti", yearStart: 2000, yearEnd: 2014 },
      { makeSlug: "subaru", modelSlug: "impreza-coupe-wrx-type-r-sti-ver-vi", yearStart: 1999, yearEnd: 2000 },
    ],
  },
  {
    name: "Integra DC2 Performance Aluminum Radiator",
    brandSlug: "mishimoto",
    categorySlug: "cooling",
    sourceName: "Mishimoto",
    sourceUrl: "https://www.mishimoto.com/mmrad-int-94-features-benefits-video.html",
    description: "Mishimoto performance aluminum radiator information for 1994-2001 Acura Integra applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "acura", modelSlug: "integra", yearStart: 1994, yearEnd: 2001 },
      { makeSlug: "acura", modelSlug: "integra-type-r", yearStart: 1997, yearEnd: 2001 },
      { makeSlug: "honda", modelSlug: "integra-type-r-dc2", yearStart: 1997, yearEnd: 2001 },
    ],
  },
  {
    name: "Lamborghini Urus 4.0TFSI V8 Intake System",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/lamborghini-urus/",
    description: "Eventuri 4.0TFSI V8 intake system for Lamborghini Urus applications with enlarged turbo inlets and sealed carbon components.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "lamborghini", modelSlug: "urus", yearStart: 2018, engine: "4.0TFSI V8" },
    ],
  },
  {
    name: "Corvette C8 Z06 Intake System",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/c8-z06-corvette/",
    description: "Eventuri intake system for Chevrolet Corvette C8 Z06 applications with enlarged intake volume and visible carbon construction.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "chevrolet", modelSlug: "corvette-c8", yearStart: 2023, trim: "Z06", engine: "LT6" },
    ],
  },
  {
    name: "Corvette C8 ZR1 Intake System",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/c8-corvette-zr1/",
    description: "Eventuri intake system for Chevrolet Corvette C8 ZR1 applications with larger turbo inlet architecture.",
    status: "ACTIVE",
    estimatedHpGain: 36,
    estimatedTorqueGain: 101,
    gainBasis: "Source states peak gains of 36 whp and 101 ft-lb, with larger midrange gains.",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "chevrolet", modelSlug: "corvette-c8", yearStart: 2025, trim: "ZR1", engine: "LT7" },
    ],
  },
  {
    name: "350Z Z33 Full Dual Exhaust",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/muffler/db/15325",
    partNumber: "32009-BN001",
    description: "HKS Full Dual exhaust for Nissan 350Z Z33 VQ35DE applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "350z", yearStart: 2002, yearEnd: 2007, engine: "VQ35DE" },
      { makeSlug: "nissan", modelSlug: "fairlady-z-version-s-z33", yearStart: 2002, yearEnd: 2007, engine: "VQ35DE" },
    ],
  },
  {
    name: "370Z Z34 Full Dual Exhaust",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/muffler/db/15326",
    partNumber: "32009-BN004",
    description: "HKS Full Dual exhaust for Nissan 370Z Z34 VQ37VHR applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "370z", yearStart: 2008, yearEnd: 2021, engine: "VQ37VHR" },
      { makeSlug: "nissan", modelSlug: "fairlady-z-z34", yearStart: 2008, yearEnd: 2021, engine: "VQ37VHR" },
    ],
  },
  {
    name: "Skyline GT-R GT III Sports Turbine Kit",
    brandSlug: "hks",
    categorySlug: "forced-induction",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/turbo/db/17761",
    partNumber: "11004-AN011",
    description: "HKS GT III sports turbine kit for Skyline GT-R RB26DETT applications.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "skyline-gt-r", yearStart: 1989, yearEnd: 2002, engine: "RB26DETT" },
      { makeSlug: "nissan", modelSlug: "r32-gt-r-nismo", yearStart: 1989, yearEnd: 1994, engine: "RB26DETT" },
      { makeSlug: "nissan", modelSlug: "r33-gt-r-v-spec", yearStart: 1995, yearEnd: 1998, engine: "RB26DETT" },
      { makeSlug: "nissan", modelSlug: "r34-gt-r-v-spec-ii-n-r", yearStart: 1999, yearEnd: 2002, engine: "RB26DETT" },
    ],
  },
  {
    name: "GT-R R35 Legamax Premium Exhaust",
    brandSlug: "hks",
    categorySlug: "exhaust",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/muffler/db/11992",
    partNumber: "31021-AN010",
    description: "HKS Legamax Premium exhaust for Nissan GT-R R35 VR38DETT applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "gt-r", yearStart: 2007, yearEnd: 2019, engine: "VR38DETT" },
      { makeSlug: "nissan", modelSlug: "gt-r-nismo", yearStart: 2007, yearEnd: 2019, engine: "VR38DETT" },
      { makeSlug: "nissan", modelSlug: "gt-r-premium-edition-t-spec", yearStart: 2007, yearEnd: 2019, engine: "VR38DETT" },
    ],
  },
  {
    name: "Roadster ND GT2 Supercharger Pro Kit",
    brandSlug: "hks",
    categorySlug: "forced-induction",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/supercharger/db/21251",
    description: "HKS GT2 supercharger pro kit for Mazda Roadster and MX-5 2.0-liter ND applications.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "mazda", modelSlug: "roadster-s-nd", yearStart: 2016, engine: "SKYACTIV-G 2.0" },
      { makeSlug: "mazda", modelSlug: "roadster-nr-a-nd", yearStart: 2016, engine: "SKYACTIV-G 2.0" },
      { makeSlug: "mazda", modelSlug: "mx-5-miata", yearStart: 2016, engine: "SKYACTIV-G 2.0" },
      { makeSlug: "mazda", modelSlug: "miata", yearStart: 2016, engine: "SKYACTIV-G 2.0" },
    ],
  },
  {
    name: "Fairlady Z Z34 AT Fluid Cooler Kit",
    brandSlug: "hks",
    categorySlug: "cooling",
    sourceName: "HKS",
    sourceUrl: "https://www.hks-power.co.jp/en/product_db/cooling/db/10981",
    description: "HKS automatic transmission fluid cooler kit for Nissan Fairlady Z Z34 sport driving applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "nissan", modelSlug: "370z", yearStart: 2008, yearEnd: 2021, engine: "VQ37VHR", notes: "Automatic transmission fitment." },
      { makeSlug: "nissan", modelSlug: "fairlady-z-z34", yearStart: 2008, yearEnd: 2021, engine: "VQ37VHR", notes: "Automatic transmission fitment." },
    ],
  },
  {
    name: "Ferrari Roma Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/ferrari/roma-2/roma/",
    imageUrl: "https://www.novitecgroup.com/assets/images/news/ferrari/ROMA/headerbilder__FocusFillWyIwLjAwIiwiMC4wMCIsMTkyMCw2MDBd.jpg",
    description: "NOVITEC refinement program for Ferrari Roma including performance exhaust, carbon aero, forged wheels, and suspension options.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "ferrari", modelSlug: "roma", yearStart: 2020 },
    ],
  },
  {
    name: "Ferrari SF90 Stradale Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/ferrari/sf90/sf90-stradale/",
    imageUrl: "https://www.novitecgroup.com/assets/images/slider/headersf901000__FocusFillWyIwLjAwIiwiMC4wMCIsMTkyMCw2MDBd.jpg",
    description: "NOVITEC refinement program for Ferrari SF90 Stradale with engine controls, high-performance exhaust, carbon aero, wheels, and springs.",
    status: "ACTIVE",
    estimatedHpGain: 109,
    gainBasis: "Source states modified engine controls and exhaust deliver an 80 kW / 109 hp increase.",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "ferrari", modelSlug: "sf90-stradale", yearStart: 2020 },
    ],
  },
  {
    name: "Ferrari 812 Superfast Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/ferrari/812/812-superfast/",
    imageUrl: "https://www.novitecgroup.com/assets/images/slider/Ferrari/812-nlargo/812-header__FocusFillWyIwLjAwIiwiMC4wMCIsMTkyMCw2MDBd.jpg",
    description: "NOVITEC high-performance exhaust, aero, wheel, suspension, and front-lift program for Ferrari 812 Superfast.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "ferrari", modelSlug: "812-superfast", yearStart: 2017 },
    ],
  },
  {
    name: "Ferrari 458 Italia Inconel Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/ferrari/458/458-italia/",
    imageUrl: "https://www.novitecgroup.com/assets/images/slider/Ferrari/458-italia/4581__FocusFillWyIwLjAwIiwiMC4wMCIsMTkyMCw2MDBd.jpg",
    description: "NOVITEC high-performance Inconel exhaust and aerodynamic enhancement program for Ferrari 458 Italia.",
    status: "ACTIVE",
    gainBasis: "Source states the Inconel exhaust optimizes power yield and weighs 21 kg less than the production exhaust.",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "ferrari", modelSlug: "458-italia", yearStart: 2009, yearEnd: 2015 },
    ],
  },
  {
    name: "Lamborghini Aventador Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/lamborghini/aventador/aventador/",
    imageUrl: "https://www.novitecgroup.com/assets/images/slider/lamborghini/aventador/header-1__FocusFillWyIwLjAwIiwiMC4wMCIsMTkyMCw2MDBd.jpg",
    description: "NOVITEC performance exhaust, upgraded engine management, aero, wheels, and suspension program for Lamborghini Aventador.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "lamborghini", modelSlug: "aventador", yearStart: 2011 },
      { makeSlug: "lamborghini", modelSlug: "aventador-lp-700-4", yearStart: 2011 },
    ],
  },
  {
    name: "Lamborghini Aventador SV Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/lamborghini/aventador/aventador-sv/",
    imageUrl: "https://www.novitecgroup.com/assets/images/slider/lamborghini/aventador/sv-header__FocusFillWyIwLjAwIiwiMC4wMCIsMTkyMCw2MDBd.jpg",
    description: "NOVITEC sport exhaust and refinement program for Lamborghini Aventador SV applications.",
    status: "ACTIVE",
    gainBasis: "Source states performance output of 578 kW / 786 hp and 738 Nm with the refinement program.",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "lamborghini", modelSlug: "aventador-lp-750-4-sv", yearStart: 2015, yearEnd: 2017 },
    ],
  },
  {
    name: "McLaren 720S Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/mclaren/720-s/720-s/",
    imageUrl: "https://www.novitecgroup.com/assets/images/slider/mclaren/720s-header__FocusFillWyIwLjAwIiwiMC4wMCIsMTkyMCw2MDBd.jpg",
    description: "NOVITEC performance tuning, race exhaust, forged wheels, and suspension program for McLaren 720S.",
    status: "ACTIVE",
    gainBasis: "Source states peak output up to 592 kW / 806 hp and 878 Nm.",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "mclaren", modelSlug: "720s", yearStart: 2017 },
    ],
  },
  {
    name: "McLaren 570S Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/mclaren/570/540c-570s-gt-spider/",
    imageUrl: "https://www.novitecgroup.com/assets/images/slider/mclaren/570/s-header-1__FocusFillWyIwLjAwIiwiMC4wMCIsMTkyMCw2MDBd.jpg",
    description: "NOVITEC aerodynamic, wheel, spring, engine tuning, and high-performance exhaust program for McLaren 570S applications.",
    status: "ACTIVE",
    gainBasis: "Source states engine tuning up to 475 kW / 646 hp and a top speed of 335 km/h.",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "mclaren", modelSlug: "570s", yearStart: 2015, yearEnd: 2021 },
      { makeSlug: "mclaren", modelSlug: "gt", yearStart: 2016, yearEnd: 2021, notes: "Source page includes the 570GT family." },
    ],
  },
  {
    name: "McLaren 750S Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/mclaren/750s-2/750s/",
    imageUrl: "https://www.novitecgroup.com/assets/images/news/mclaren/750s-full/750sheader__FocusFillWyIwLjAwIiwiMC4wMCIsMTkyMCw2MDBd.jpg",
    description: "NOVITEC performance tuning, race exhaust, forged wheels, aero, and suspension program for McLaren 750S.",
    status: "ACTIVE",
    gainBasis: "Source states tuning stages up to 618 kW / 840 hp and 889 Nm.",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "mclaren", modelSlug: "750s", yearStart: 2024 },
    ],
  },
  {
    name: "McLaren Senna Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/mclaren/senna/",
    imageUrl: "https://www.novitecgroup.com/assets/images/slider/mclaren/senna-header__FocusFillWyIwLjAwIiwiMC4wMCIsMTkyMCw2MDBd.jpg",
    description: "NOVITEC tuning range for McLaren Senna with performance increase, forged wheels, and lightweight Inconel exhaust.",
    status: "ACTIVE",
    gainBasis: "Source states output up to 663 kW / 902 hp and 888 Nm.",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "mclaren", modelSlug: "senna", yearStart: 2018 },
    ],
  },
  {
    name: "Porsche 911 GT3 RS 992 KW V7 Racing Suspension",
    brandSlug: "kw-suspensions",
    categorySlug: "suspension",
    sourceName: "KW Suspensions",
    sourceUrl: "https://www.kwsuspensions.com/de-en/lp-porsche-911-gt3-rs-typ-992",
    imageUrl: "https://dsahg7sfz-res.cloudinary.com/image/upload/t_1208px%20Technikverliebt/f_auto/q_auto/v1775127864/LP_Banner_Shop_vjyzn1.jpg",
    description: "KW V7 Racing suspension program for Porsche 911 GT3 RS type 992 with motorsport-style damper adjustment.",
    status: "ACTIVE",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "porsche", modelSlug: "911-gt3-rs-992", yearStart: 2023 },
    ],
  },
  {
    name: "BMW E46 M3 Carbon Intake",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "Eventuri",
    sourceUrl: "https://www.eventuri.net/product/bmw-e46-m3/",
    imageUrl: "https://www.eventuri.net/wp-content/uploads/2025/10/15355901254_20f9d36a7e_o.webp",
    description: "Eventuri carbon intake system for BMW E46 M3 S54 applications.",
    status: "ACTIVE",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "bmw", modelSlug: "m3-e46", yearStart: 2000, yearEnd: 2006, engine: "S54" },
      { makeSlug: "bmw", modelSlug: "m3", yearStart: 2000, yearEnd: 2006, engine: "S54" },
      { makeSlug: "bmw", modelSlug: "3-series-e46", yearStart: 2000, yearEnd: 2006, engine: "S54" },
    ],
  },
  {
    name: "Audi 8S TTS Carbon Intake System",
    brandSlug: "eventuri",
    categorySlug: "intake",
    sourceName: "IND Distribution / Eventuri",
    sourceUrl: "https://ind-distribution.com/products/eventuri-audi-8y-s3-8s-tts-black-carbon-intake-system",
    imageUrl: "https://ind-distribution.com/cdn/shop/products/51921615627_21eb664daf_b_2c7a190c-deb9-43dc-b429-c25126853877.jpg?v=1772072030",
    partNumber: "EVE-8YS3-CF-INT",
    description: "Eventuri black carbon intake system for Audi 8S TTS and 8Y S3 fitments.",
    status: "ACTIVE",
    retailPriceCents: 149500,
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "audi", modelSlug: "tts-coup", yearStart: 2015, trim: "8S TTS" },
      { makeSlug: "audi", modelSlug: "tt-coup-3-2-quattro", yearStart: 2015, trim: "8S TT platform", notes: "Catalog model used for Audi TT coupe family coverage." },
    ],
  },
  {
    name: "Ferrari 488 GTB Performance Exhaust Program",
    brandSlug: "novitec",
    categorySlug: "exhaust",
    sourceName: "NOVITEC",
    sourceUrl: "https://www.novitecgroup.com/en/brands/ferrari/488/488-gtb/",
    imageUrl: "https://www.novitecgroup.com/assets/images/slider/Ferrari/488-gtb/488-btb-header-1__FocusFillWyIwLjAwIiwiMC4wMCIsMTkyMCw2MDBd.jpg",
    description: "NOVITEC refinement program for Ferrari 488 GTB including performance exhaust, aero, wheels, suspension, and tuning options.",
    status: "ACTIVE",
    gainBasis: "Source states tuning output up to 568 kW / 772 hp for the 488 GTB program.",
    installComplexity: "PRO_ONLY",
    compatibility: [
      { makeSlug: "ferrari", modelSlug: "488-gtb", yearStart: 2015, yearEnd: 2020 },
    ],
  },
  {
    name: "Ferrari 488 Pista Style Intake Charge Pipes",
    brandSlug: "fabspeed",
    categorySlug: "intake",
    sourceName: "Fabspeed Motorsport",
    sourceUrl: "https://www.fabspeed.com/fabspeed-ferrari-488-pista-style-intake-charge-pipes/",
    imageUrl: "https://cdn11.bigcommerce.com/s-fh9wsjv2/products/1295/images/15579/fabspeed-motorsport-fabspeed-ferrari-488-pista-style-intake-charge-pipes__98911.1718981909.500.664.jpg?c=2",
    description: "Fabspeed Ferrari 488 Pista-style intake charge pipes replacing OEM plastic charge pipes with mandrel-bent aluminum.",
    status: "ACTIVE",
    retailPriceCents: 193295,
    estimatedHpGain: 21,
    estimatedTorqueGain: 23,
    gainBasis: "Source states +21 WHP and +23 ft-lb torque.",
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "ferrari", modelSlug: "488-gtb", yearStart: 2015, yearEnd: 2020, engine: "F154 twin-turbo V8" },
    ],
  },
  {
    name: "Ferrari 488 GTB Carbon Fiber Cold Air Intake",
    brandSlug: "armaspeed",
    categorySlug: "intake",
    sourceName: "ARMASPEED",
    sourceUrl: "https://www.armaspeed.com/product/ferrari-488-armaspeed-carbon-fiber-cold-air-intake/",
    imageUrl: "https://www.armaspeed.com/wp-content/uploads/2021/11/AA4A5237_O-scaled.jpg",
    partNumber: "ARMAFER488-A",
    description: "ARMASPEED carbon fiber cold air intake for Ferrari 488 GTB 3.9-liter twin-turbo applications.",
    status: "ACTIVE",
    retailPriceCents: 510000,
    installComplexity: "SHOP_RECOMMENDED",
    compatibility: [
      { makeSlug: "ferrari", modelSlug: "488-gtb", yearStart: 2015, yearEnd: 2020, engine: "F154 twin-turbo V8" },
    ],
  },
];

async function main() {
  const createdOrUpdated: string[] = [];
  const missingCompatibility: string[] = [];

  for (const seed of REAL_PART_BATCH) {
    const [category, brand] = await Promise.all([
      prisma.partCategory.findUnique({ where: { slug: seed.categorySlug } }),
      prisma.partBrand.findUnique({ where: { slug: seed.brandSlug } }),
    ]);

    if (!category) throw new Error(`Missing part category: ${seed.categorySlug}`);
    if (!brand) throw new Error(`Missing part brand: ${seed.brandSlug}`);

    const part = await prisma.performancePart.upsert({
      where: {
        brandId_slug: {
          brandId: brand.id,
          slug: toPartSlug(seed.name),
        },
      },
      update: {
        categoryId: category.id,
        name: seed.name,
        partNumber: seed.partNumber ?? null,
        description: seed.description,
        sourceUrl: seed.sourceUrl,
        ...(seed.imageUrl ? { imageUrl: seed.imageUrl } : {}),
        sourceName: seed.sourceName,
        sourceConfidence: "SOURCE_VERIFIED",
        status: seed.status ?? "ACTIVE",
        retailPriceCents: seed.retailPriceCents ?? null,
        estimatedHpGain: seed.estimatedHpGain ?? null,
        estimatedTorqueGain: seed.estimatedTorqueGain ?? null,
        gainBasis: seed.gainBasis ?? null,
        installComplexity: seed.installComplexity ?? "SHOP_RECOMMENDED",
        trackingStatus: "NOT_CONFIGURED",
      },
      create: {
        categoryId: category.id,
        brandId: brand.id,
        name: seed.name,
        slug: toPartSlug(seed.name),
        partNumber: seed.partNumber ?? null,
        description: seed.description,
        sourceUrl: seed.sourceUrl,
        imageUrl: seed.imageUrl ?? null,
        sourceName: seed.sourceName,
        sourceConfidence: "SOURCE_VERIFIED",
        status: seed.status ?? "ACTIVE",
        retailPriceCents: seed.retailPriceCents ?? null,
        estimatedHpGain: seed.estimatedHpGain ?? null,
        estimatedTorqueGain: seed.estimatedTorqueGain ?? null,
        gainBasis: seed.gainBasis ?? null,
        installComplexity: seed.installComplexity ?? "SHOP_RECOMMENDED",
        trackingStatus: "NOT_CONFIGURED",
      },
    });

    for (const fitment of seed.compatibility) {
      const make = await prisma.make.findUnique({ where: { slug: fitment.makeSlug } });
      if (!make) {
        missingCompatibility.push(`${seed.name}: missing make ${fitment.makeSlug}`);
        continue;
      }

      const model = fitment.modelSlug
        ? await prisma.model.findUnique({
            where: {
              makeId_slug: {
                makeId: make.id,
                slug: fitment.modelSlug,
              },
            },
          })
        : null;

      if (fitment.modelSlug && !model) {
        missingCompatibility.push(`${seed.name}: missing model ${fitment.makeSlug}/${fitment.modelSlug}`);
        continue;
      }

      const compatibilityScope = {
        partId: part.id,
        makeId: make.id,
        modelId: model?.id ?? null,
        yearStart: fitment.yearStart ?? null,
        yearEnd: fitment.yearEnd ?? null,
        trim: fitment.trim ?? null,
        engine: fitment.engine ?? null,
      };

      const existingCompatibility = await prisma.partCompatibility.findFirst({
        where: compatibilityScope,
        select: { id: true },
      });

      if (existingCompatibility) {
        await prisma.partCompatibility.update({
          where: { id: existingCompatibility.id },
          data: {
            notes: fitment.notes ?? null,
            confidence: "SOURCE_VERIFIED",
          },
        });
      } else {
        await prisma.partCompatibility.create({
          data: {
            ...compatibilityScope,
            notes: fitment.notes ?? null,
            confidence: "SOURCE_VERIFIED",
          },
        });
      }
    }

    createdOrUpdated.push(`${brand.name} ${seed.name}`);
  }

  const [activeParts, sourceVerifiedParts, compatibilityRows] = await Promise.all([
    prisma.performancePart.count({ where: { status: "ACTIVE" } }),
    prisma.performancePart.count({ where: { sourceConfidence: "SOURCE_VERIFIED" } }),
    prisma.partCompatibility.count({ where: { confidence: "SOURCE_VERIFIED" } }),
  ]);

  console.log(JSON.stringify({
    imported: createdOrUpdated.length,
    activeParts,
    sourceVerifiedParts,
    sourceVerifiedCompatibilityRows: compatibilityRows,
    missingCompatibility,
  }, null, 2));
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
